baseURL = "http://election-guide.news.baltimoresun.com/"
buildDrafts = false
canonifyURLs = true
contentDir = "content"
disableHugoGeneratorInject = true
languageCode = "en-us"
layoutDir = "layouts"
publishDir = "public"
title = "Election Guide 2018 | Baltimore Sun"

[Params]
Year = 2018
