baseURL = "http://election-guide.news.baltimoresun.com/"
buildDrafts = false
canonifyURLs = true
contentDir = "content"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy","taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
publishDir = "public"
title = "Baltimore Sun Election Guide 2018"
staticDir = ["static", "dist"]

[Params]
DefaultShareText = "Learn about primary elections in Maryland in the Baltimore Sun 2018 Voter Guide:"
icon = "images/icon.png"
image = "images/icon.png"
omniture-page-name = "bs:data:news:maryland:politics:voter-guide-2018:dataproject"
omniture-channel = "news:maryland:politics"
Year = 2018
