baseURL = "https://elections2018.news.baltimoresun.com/"
buildDrafts = false
canonifyURLs = true
contentDir = "content"
disableHugoGeneratorInject = true
disableFastRender = true
disableKinds = ["taxonomy","taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
publishDir = "public"
title = "Baltimore Sun Election Guide 2018"
staticDir = ["static", "dist"]

[Params]
share-text = "Learn more about the upcoming election in the Baltimore Sun’s 2018 Maryland Voter Guide"
icon = "images/voter-guide-square-200.png"
image = "images/voter-guide-square.png"
omniture-page-name = "bs:newsserver:elections2018:news:maryland:politics:voter-guide-2018:dataproject"
omniture-channel = "news:maryland:politics"
omniture-server = "elections2018.news.baltimoresun.com"
results-base-url = "https://news.baltimoresun.com/results/"
Year = 2018


[[menu.main]]
url = "http://www.baltimoresun.com/news/maryland/politics/"
name = "Election Coverage"
weight = 1

[[menu.main]]
url = "/candidates/"
name = "Candidates"
weight = 2

[[menu.main]]
url = "/dates/"
name = "Key Dates"
weight = 3

[[menu.main]]
url = "http://mdelect.net/"
name = "Find District"
weight = 4

[[menu.main]]
url = "/about/"
name = "About Questionnaires"
weight = 5

[[menu.main]]
url = "http://www.tribpub.com/central-terms-of-service/"
name = "Terms"
weight = 6

[[menu.main]]
url = "http://www.tribpub.com/privacy-policy-and-your-privacy-rights/"
name = "Privacy"
weight = 7

[[menu.main]]
url = "mailto:elections@baltsun.com"
name = "Feedback"
weight = 8
