baseURL = "http://election-guide.news.baltimoresun.com/"
buildDrafts = false
canonifyURLs = true
contentDir = "content"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy","taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
publishDir = "public"
title = "Election Guide 2018 | Baltimore Sun"
staticDir = ["static", "dist"]

[Params]
Year = 2018
DefaultShareText = "Learn about primary elections in Maryland in the Baltimore Sun 2018 Voter Guide:"
