baseURL = "http://election-guide.news.baltimoresun.com/"
buildDrafts = false
canonifyURLs = true
contentDir = "content"
languageCode = "en-us"
layoutDir = "layouts"
publishDir = "public"
title = "Election Guide 2016 | Baltimore Sun"
